#!/bin/sh
CWD=`pwd`
TMP=//dev/shm/tmp
PKG=$TMP/package-arts

VERSION=${VERSION:-1.5.10}
ARCH=${ARCH:-i486}
BUILD=${BUILD:-olo6}
CPUOPT="-O2 -fpermissive -march=i686 -std=c99"


rm -rf $PKG
mkdir -p $PKG/usr

# Avoid a version number in .la files:
if [ -d /opt/kde/lib/qt3 ]; then
  QTDIR=/opt/kde/lib/qt3
fi
cd $TMP
echo "Building arts-$VERSION.tar.bz2..."
tar xvf $CWD/arts-$VERSION.tar.bz2
cd arts-$VERSION

zcat $CWD/arts.tmpdir.diff.gz | patch -p1 --verbose || exit 1
cat $CWD/alsa-11-conf2.diff | patch -p0 --verbose || exit 1
cat $CWD/ainclude.patch | patch -p0 || exit 1
cat $CWD/patch-g++48.diff | patch -p0 || exit 1

#autoreconf -vfi


chown -R root:root .
CFLAGS=$CPUOPT \
CXXFLAGS=$CPUOPT \
./configure \
  --disable-dependency-tracking \
  --prefix=/usr \
  --sysconfdir=/etc \
  --with-xinerama \
  --with-alsa \
  --with-jack \
  --disable-debug \
  --program-prefix="" \
  --program-suffix="" \
  --build=$ARCH-slackware-linux

make -j 3 || exit 1 

make install DESTDIR=$PKG
mkdir -p $PKG/usr/doc/arts-$VERSION
cp -a \
  COPYING COPYING.LIB INSTALL doc/NEWS doc/README doc/TODO \
  $PKG/usr/doc/arts-$VERSION
mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)
if [ -d $PKG/usr/man ]; then
  gzip -9 $PKG/usr/man/man?/*
fi

cd $PKG
makepkg -l y -c n ../arts-$VERSION-$ARCH-$BUILD.txz

