#define KDE_USE_FINAL 1
#include "dimgloader.cpp"
#include "pngloader.cpp"
#include "jpegloader.cpp"
#include "tiffloader.cpp"
#include "rawloader.cpp"
#include "ppmloader.cpp"
#include "qimageloader.cpp"
#include "jp2kloader.cpp"
#include "jpegsettings.cpp"
#include "pngsettings.cpp"
#include "tiffsettings.cpp"
#include "jp2ksettings.cpp"
