/****************************************************************************
**
** DCOP Skeleton generated by dcopidl2cpp from knetworkconfiface.kidl
**
** WARNING! All changes made in this file will be lost!
**
*****************************************************************************/

#include "./knetworkconfiface.h"

#include <kdatastream.h>


static const char* const KNetworkConfIface_ftable[1][3] = {
    { 0, 0, 0 }
};

bool KNetworkConfIface::process(const QCString &fun, const QByteArray &data, QCString& replyType, QByteArray &replyData)
{
	return DCOPObject::process( fun, data, replyType, replyData );
}

QCStringList KNetworkConfIface::interfaces()
{
    QCStringList ifaces = DCOPObject::interfaces();
    ifaces += "KNetworkConfIface";
    return ifaces;
}

QCStringList KNetworkConfIface::functions()
{
    QCStringList funcs = DCOPObject::functions();
    for ( int i = 0; KNetworkConfIface_ftable[i][2]; i++ ) {
	QCString func = KNetworkConfIface_ftable[i][0];
	func += ' ';
	func += KNetworkConfIface_ftable[i][2];
	funcs << func;
    }
    return funcs;
}


