#!/bin/sh
#
# Heavily based on the Slackware 12.2 SlackBuild
# http://sourceforge.net/projects/powersave/
# Packager neongen ( neongen at libero.it)
# http://www.slacky.eu

CWD=`pwd`
if [ "$TMP" = "" ]; then
  TMP=/tmp
fi

NAME=kpowersave
VERSION=0.7.3
ARCH=${ARCH:-i686}
CHOST=i486
BUILD=3ng
PKG=$TMP/package-$NAME
SOURCE=http://heanet.dl.sourceforge.net/sourceforge/powersave/$NAME-$VERSION.tar.bz2

if [ "$ARCH" = "i386" ]; then
  SLKCFLAGS="-O2 -march=i386 -mcpu=i686"
elif [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2"
fi

if [ ! -d $TMP ]; then
  mkdir -p $TMP
fi
if [ ! -d $PKG ]; then
  mkdir -p $PKG
fi


echo "+=============================================================================="
echo "| $NAME-$VERSION"
echo "+=============================================================================="

if [ ! -e $NAME-$VERSION.tar.bz2 ]; then
	echo "Downloading source"
	wget -c $SOURCE
fi

cd $TMP

echo "Unpacking $NAME..."
tar -xjf $CWD/$NAME-$VERSION.tar.bz2

cd $NAME-$VERSION

find . -perm 777 -exec chmod 755 {} \;
find . -perm 775 -exec chmod 755 {} \;
find . -perm 555 -exec chmod 755 {} \;
find . -perm 666 -exec chmod 644 {} \;
find . -perm 664 -exec chmod 644 {} \;
find . -perm 444 -exec chmod 644 {} \;
#cd $NAME
#chown -R root:root .
cat $CWD/kubuntu_02_messages_target.diff.diff | patch -p1
cat $CWD/05-battery_rescan.patch.diff | patch -p1
cat $CWD/06-buildsystem_fixes.patch.diff | patch -p1
cat $CWD/hardware_cpu_fix.diff | patch -p1
cat $CWD/inactivity_fix.diff | patch -p1

make -f admin/Makefile.common cvs

CFLAGS="$SLKCFLAGS" \
./configure  --prefix=/usr \
--disable-toggle  \
--disable-editor  \
--disable-force \
--build=$CHOST-slackware-linux
#--docdir=/usr/doc/$NAME-$VERSION \

make
make install  DESTDIR=$PKG

mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a \
 AUTHORS COPYING ChangeLog INSTALL README \
  $PKG/usr/doc/$NAME-$VERSION
mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/slack-desc > $PKG/usr/doc/$NAME-$VERSION/slack-desc
# cat $CWD/default.action-2.0 > $PKG/usr/doc/$NAME-$VERSION/default.action-2.0
# cat $CWD/slack-required > $PKG/usr/doc/$NAME-$VERSION/slack-required
cat $CWD/$NAME.SlackBuild > $PKG/usr/doc/$NAME-$VERSION/$NAME.SlackBuild

chmod 644 $PKG/usr/doc/$NAME-$VERSION/*

cd $PKG
requiredbuilder -v -y -s $CWD $PKG
makepkg -l y -c n $CWD/$NAME-$VERSION-$ARCH-$BUILD.tgz

if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/$NAME-$VERSION
  rm -rf $PKG
  rm -rf $TMP/$NAME-$VERSION.tar.gz*
fi
