#!/bin/sh

usage()
{
	echo "usage: $0 [OPTIONS]"
cat << EOH

options:
	[--libs]
	[--cflags]
	[--version]
	[--arts-version]
	[--arts-prefix]
EOH
	exit 1;
}

prefix=/usr
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include
libdl=-ldl

flags=""

while test $# -gt 0
do
  case $1 in
    --libs)
	  flags="$flags -L$libdir $libdl -lartsc  -lpthread   -lgmodule-2.0 -lgthread-2.0 -lrt -lglib-2.0  "
	  ;;
    --cflags)
	  flags="$flags -I$includedir/artsc -pthread -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  "
	  ;;
    --version)
	  echo 0.9.5
	  ;;
    --arts-version)
	  echo 1.5.10
	  ;;
    --arts-prefix)
	  echo $prefix
	  ;;
	*)
	  echo "$0: unknown option $1"
	  echo 
	  usage
	  ;;
  esac
  shift
done

if test -n "$flags"
then
  echo $flags
fi
