#!/bin/sh
CWD=`pwd`
TMP=//dev/shm/tmp
PKG=$TMP/package-amarok
CPUOPT="-O2 -march=i486 -mtune=i686"
TARGET="i486"
ARCH=$TARGET
BUILD="2"

# Set the config option variables if they are not already set:
if [ -r ../KDE.options ]; then
  . ../KDE.options
fi

# The global options may be overridden here (if needed):
if [ -r ./local.options ]; then
  . ./local.options
fi

rm -rf $PKG
mkdir -p $PKG/usr

# Avoid a version number in .la files:
if [ -d /usr/lib${LIBDIRSUFFIX}/qt3 ]; then
  QTDIR=/usr/lib${LIBDIRSUFFIX}/qt3
fi
cd $TMP
echo "Building amarok-$VERSION.tar.bz2..."
tar xjvf $CWD/amarok-$VERSION.tar.bz2

# I *hate* it when an "a" release blows off updating the directory name.  Grrrrrrrrrrrrrrrr.
# Commented out post 1.4.0a...
#cd amarok-1.4.0 || exit 1
cd amarok-$VERSION

if [ -r $CWD/apply-patches.sh ]; then
  . $CWD/apply-patches.sh
fi

make -f admin/Makefile.common

chown -R root:root .
CFLAGS=$CPUOPT \
CXXFLAGS=$CPUOPT \
./configure \
  --prefix=/usr \
  --sysconfdir=/etc \
  --with-xinerama \
  --with-libnjb \
  --with-libmtp \
  --with-libgpod \
  --with-libkarma \
  --without-daap \
  --disable-debug \
  --program-prefix="" \
  --program-suffix="" \
  --build=$TARGET-slackware-linux
make $NUMJOBS || exit 1
make install DESTDIR=$PKG
mkdir -p $PKG/usr/doc/amarok-$VERSION
cp -a \
  AUTHORS COPYING INSTALL README TODO \
  $PKG/usr/doc/amarok-$VERSION
mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)
if [ -d $PKG/usr/man ]; then
  gzip -9 $PKG/usr/man/man?/*
fi

cd $PKG
makepkg -l y -c n ../amarok-$VERSION-$ARCH-$BUILD.txz

