#!/bin/sh
CWD=`pwd`
TMP=$TMP/
PKG=$TMP/package-kdelibs

VERSION=3.5.10
CPUOPT="-O2 -march=i486"
TARGET=i486
ARCH=i486
BUILD=olo9

# Set the config option variables if they are not already set:
if [ -r ../KDE.options ]; then
  . ../KDE.options
fi

# The global options may be overridden here (if needed):
if [ -r ./local.options ]; then
  . ./local.options
fi

rm -rf $PKG
mkdir -p $PKG/usr

# Avoid a version number in .la files:
if [ -d /opt/kde/lib${LIBDIRSUFFIX}/qt3 ]; then
  QTDIR=/opt/kde/lib${LIBDIRSUFFIX}/qt3
fi

cd $TMP
echo "Building kdelibs-$VERSION.tar.bz2..."
tar xjvf $CWD/kdelibs-$VERSION.tar.bz2 || exit 1
cd kdelibs-$VERSION || exit 1

if [ -r $CWD/apply-patches.sh ]; then
  . $CWD/apply-patches.sh
fi

chown -R root:root .
CFLAGS=$CPUOPT \
CXXFLAGS=$CPUOPT \
./configure \
  --prefix=/usr \
  --sysconfdir=/etc \
  --with-ssl-dir=/usr \
  --with-xinerama \
  --disable-debug \
  --enable-dnotify \
  --enable-inotify \
  --enable-mitshm \
  --enable-sendfile \
  --enable-final \
  --program-prefix="" \
  --program-suffix="" \
  --build=$TARGET-slackware-linux

#added
sed -i -e 's|linux/inotify|sys/inotify|' \
         -e '/^static inline int inotify_init/,/^}/d' \
         -e '/^static inline int inotify_add_watch/,/^}/d' \
         -e '/^static inline int inotify_rm_watch/,/^}/d' kio/kio/kdirwatch.cpp
LD_LIBRARY_PATH="$QTDIR/lib"
#end
make $NUMJOBS || exit 1
make install DESTDIR=$PKG
mkdir -p $PKG/usr/doc/kdelibs-$VERSION
cp -a \
  AUTHORS COMPILING COMPILING.html COPYING COPYING.BSD COPYING.LIB DEBUG INSTALL KDE2PORTING.html KDE3PORTING.html NAMING README  kdelibs.lsm \
  $PKG/usr/doc/kdelibs-$VERSION
mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)
if [ -d $PKG/usr/man ]; then
  gzip -9 $PKG/usr/man/man?/*
fi

cd $PKG
makepkg -l y -c n ../kdelibs-$VERSION-$ARCH-$BUILD.txz

