#!/bin/sh
CWD=`pwd`
TMP=/tmp
PKG=$TMP/package-kdeutils
ARCH="i486"
TARGET=$ARCH
VERSION="3.5.10"
CPUOPt="-O2 -march=i486"
#BUILD="ra2"


# Set the config option variables if they are not already set:
if [ -r ../KDE.options ]; then
  . ../KDE.options
fi

# The global options may be overridden here (if needed):
if [ -r ./local.options ]; then
  . ./local.options
fi

rm -rf $PKG
mkdir -p $PKG/usr

# Avoid a version number in .la files:
if [ -d /usr/lib${LIBDIRSUFFIX}/qt3 ]; then
  QTDIR=/usr/lib${LIBDIRSUFFIX}/qt3
fi
cd $TMP
echo "Building kdeutils-$VERSION.tar.bz2..."
tar xjvf $CWD/kdeutils-$VERSION.tar.bz2 || exit 1
cd kdeutils-$VERSION || exit 1

if [ -r $CWD/apply-patches.sh ]; then
  . $CWD/apply-patches.sh
fi

chown -R root:root .
CFLAGS=$CPUOPT \
CXXFLAGS=$CPUOPT \
./configure \
  --prefix=/usr \
  --sysconfdir=/etc \
  --with-xinerama \
  --disable-debug \
  --program-prefix="" \
  --program-suffix="" \
  --build=$TARGET-slackware-linux

# fix strlcat redefinition:
sed -i 1i\ '#define HAVE_STRLCAT' ksim/monitors/snmp/snmp.cpp
sed -i 1i\ '#define HAVE_STRLCAT' ksim/monitors/snmp/value.cpp
sed -i 1i\ '#define HAVE_STRLCAT' ksim/monitors/snmp/session.cpp


make $NUMJOBS || exit 1
make install DESTDIR=$PKG
mkdir -p $PKG/usr/doc/kdeutils-$VERSION
cp -a \
  AUTHORS COPYING INSTALL README kdeutils.lsm \
  $PKG/usr/doc/kdeutils-$VERSION
mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)
if [ -d $PKG/usr/man ]; then
  gzip -9 $PKG/usr/man/man?/*
fi

cd $PKG
makepkg -l y -c n ../kdeutils-$VERSION-$ARCH-$BUILD.txz
